hydra:
  run:
    dir: outputs/qa_agent_inference/${dataset.data_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - doc_ranker: idf_topk_ranker
  - agent_prompt: hotpotqa_ircot
  - qa_prompt: hotpotqa
  - ner_model: llm_ner_model
  - el_model: colbert_el_model
  - qa_evaluator: hotpotqa

seed: 1024

dataset:
  root: ./data
  data_name: hotpotqa_test

llm:
  _target_: gfmrag.llms.ChatGPT
  model_name_or_path: gpt-3.5-turbo
  retry: 5

graph_retriever:
  model_path: rmanluo/GFM-RAG-8M
  doc_ranker: ${doc_ranker}
  ner_model: ${ner_model}
  el_model: ${el_model}
  qa_evaluator: ${qa_evaluator}
  init_entities_weight: True


test:
  top_k: 10
  max_steps: 2
  max_test_samples: -1 # -1 for all
  resume: null
